POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "hyunwook123",
  "password": "1234"
}

###

POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "hashswan123",
  "password": "1234"
}

###

DELETE http://localhost:8080/users/
