spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meme_library
    username: postgres
    password: ${DB_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-n6lgjqpsv3qu74s0.us.auth0.com/

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

  mvc:
    hiddenmethod:
      filter:
        enabled: true

auth0:
  audience: https://meme-backend-api

server:
  port: 8080